"""forbidden_words 抖音汽车直播违禁词库 seed（P0-违禁词数据迁移）

Revision ID: 0037
Revises: 0036

来源：FORBIDDEN_WORDS_DOUYIN_LIVE_SOURCE.md 第4节（403 条）。
规则：排除单字符（最/V）；qq/QQ casefold 去重；safe_word 全 NULL；
词库 scope=global 缺失才新增；词条 ON CONFLICT DO NOTHING 不覆盖已有运营状态；
downgrade 不删除词条，只回退版本标记。
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0037"
down_revision = "0036"
branch_labels = None
depends_on = None


# (library_key, word) → severity 字典（403 条，已规范化）
_SEED = {
    ('used_car_sales_base', '故事车'): "high",
    ('used_car_sales_base', '事故车'): "high",
    ('used_car_sales_base', '瑕疵'): "medium",
    ('used_car_sales_base', '改装'): "high",
    ('used_car_sales_base', '报废'): "high",
    ('used_car_sales_base', '抵押车'): "high",
    ('used_car_sales_base', '换件'): "high",
    ('used_car_sales_base', '过不了户'): "critical",
    ('used_car_sales_base', '收车'): "high",
    ('used_car_sales_base', '回收'): "high",
    ('used_car_sales_base', '二手车回收'): "high",
    ('used_car_sales_base', '加装'): "medium",
    ('used_car_sales_base', '升级'): "medium",
    ('used_car_sales_base', '改款'): "medium",
    ('used_car_sales_base', '车衣'): "medium",
    ('used_car_sales_base', '贴膜'): "medium",
    ('used_car_sales_base', '车膜'): "medium",
    ('used_car_sales_base', '车贴'): "medium",
    ('used_car_sales_base', '轮毂'): "medium",
    ('used_car_sales_base', '购置税'): "high",
    ('used_car_sales_base', '购置税全免'): "high",
    ('used_car_sales_base', '卖车'): "high",
    ('finance_compliance', '分期'): "high",
    ('finance_compliance', '贷款'): "high",
    ('finance_compliance', '置换'): "high",
    ('finance_compliance', '抵押'): "high",
    ('finance_compliance', '征信'): "high",
    ('finance_compliance', '按揭'): "high",
    ('finance_compliance', '黑户'): "critical",
    ('finance_compliance', '金融'): "high",
    ('finance_compliance', '首付'): "high",
    ('finance_compliance', '利息'): "high",
    ('finance_compliance', '利率'): "high",
    ('finance_compliance', '免息'): "high",
    ('finance_compliance', '0首付'): "critical",
    ('finance_compliance', '免首付'): "critical",
    ('finance_compliance', '投资回报'): "medium",
    ('finance_compliance', '众筹'): "high",
    ('finance_compliance', '千亿价值'): "high",
    ('finance_compliance', '价值洼地'): "medium",
    ('finance_compliance', '价值天成'): "medium",
    ('finance_compliance', '抄涨'): "high",
    ('finance_compliance', '炒股不如买房'): "high",
    ('vehicle_condition_risk', '纯天然'): "medium",
    ('vehicle_condition_risk', '祖传'): "medium",
    ('vehicle_condition_risk', '特效'): "medium",
    ('vehicle_condition_risk', '无敌'): "medium",
    ('vehicle_condition_risk', '质量免检'): "high",
    ('vehicle_condition_risk', '无需国家质量检测'): "high",
    ('vehicle_condition_risk', '免抽检'): "high",
    ('vehicle_condition_risk', '样板间实景图'): "low",
    ('vehicle_condition_risk', '效果图'): "low",
    ('extreme_ad_words', '最佳'): "medium",
    ('extreme_ad_words', '最具'): "medium",
    ('extreme_ad_words', '最爱'): "medium",
    ('extreme_ad_words', '最赚'): "medium",
    ('extreme_ad_words', '最优'): "medium",
    ('extreme_ad_words', '最优秀'): "medium",
    ('extreme_ad_words', '最好'): "medium",
    ('extreme_ad_words', '最大'): "medium",
    ('extreme_ad_words', '最大程度'): "medium",
    ('extreme_ad_words', '最高'): "medium",
    ('extreme_ad_words', '最高级'): "medium",
    ('extreme_ad_words', '最高档'): "medium",
    ('extreme_ad_words', '最高端'): "medium",
    ('extreme_ad_words', '最奢侈'): "medium",
    ('extreme_ad_words', '最低'): "medium",
    ('extreme_ad_words', '最低级'): "medium",
    ('extreme_ad_words', '最低价'): "medium",
    ('extreme_ad_words', '最底'): "medium",
    ('extreme_ad_words', '最便宜'): "medium",
    ('extreme_ad_words', '史上最低价'): "high",
    ('extreme_ad_words', '时尚最低价'): "high",
    ('extreme_ad_words', '最流行'): "medium",
    ('extreme_ad_words', '最受欢迎'): "medium",
    ('extreme_ad_words', '最时尚'): "medium",
    ('extreme_ad_words', '最聚拢'): "medium",
    ('extreme_ad_words', '最符合'): "medium",
    ('extreme_ad_words', '最舒适'): "medium",
    ('extreme_ad_words', '最先'): "medium",
    ('extreme_ad_words', '最先进'): "medium",
    ('extreme_ad_words', '最先进科学'): "medium",
    ('extreme_ad_words', '最先进加工工艺'): "medium",
    ('extreme_ad_words', '最先享受'): "medium",
    ('extreme_ad_words', '最后'): "medium",
    ('extreme_ad_words', '最后一波'): "high",
    ('extreme_ad_words', '最新'): "medium",
    ('extreme_ad_words', '最新科技'): "medium",
    ('extreme_ad_words', '最新科学'): "medium",
    ('extreme_ad_words', '最新技术'): "medium",
    ('extreme_ad_words', '第一'): "medium",
    ('extreme_ad_words', '中国第一'): "high",
    ('extreme_ad_words', '全网第一'): "high",
    ('extreme_ad_words', '销量第一'): "high",
    ('extreme_ad_words', '排名第一'): "medium",
    ('extreme_ad_words', '唯一'): "medium",
    ('extreme_ad_words', '第一品牌'): "medium",
    ('extreme_ad_words', 'NO.1'): "medium",
    ('extreme_ad_words', 'TOP1'): "medium",
    ('extreme_ad_words', '独一无二'): "medium",
    ('extreme_ad_words', '全国第一'): "high",
    ('extreme_ad_words', '一流'): "medium",
    ('extreme_ad_words', '一天'): "medium",
    ('extreme_ad_words', '仅此一次'): "high",
    ('extreme_ad_words', '全国X大品牌之一'): "medium",
    ('extreme_ad_words', '销冠'): "medium",
    ('extreme_ad_words', '国家级'): "high",
    ('extreme_ad_words', '国际级'): "high",
    ('extreme_ad_words', '全球级'): "high",
    ('extreme_ad_words', '宇宙级'): "high",
    ('extreme_ad_words', '世界级'): "high",
    ('extreme_ad_words', '千万级'): "medium",
    ('extreme_ad_words', '百万级'): "medium",
    ('extreme_ad_words', '星级'): "medium",
    ('extreme_ad_words', '甲级'): "medium",
    ('extreme_ad_words', '超甲级'): "medium",
    ('extreme_ad_words', '顶级'): "medium",
    ('extreme_ad_words', '顶尖'): "medium",
    ('extreme_ad_words', '尖端'): "medium",
    ('extreme_ad_words', '顶级工艺'): "medium",
    ('extreme_ad_words', '顶级享受'): "medium",
    ('extreme_ad_words', '高级'): "medium",
    ('extreme_ad_words', '极品'): "medium",
    ('extreme_ad_words', '极佳'): "medium",
    ('extreme_ad_words', '绝佳'): "medium",
    ('extreme_ad_words', '终极'): "medium",
    ('extreme_ad_words', '极致'): "medium",
    ('extreme_ad_words', '致极'): "medium",
    ('extreme_ad_words', '极具'): "medium",
    ('extreme_ad_words', '首个'): "medium",
    ('extreme_ad_words', '首选'): "medium",
    ('extreme_ad_words', '全球首发'): "high",
    ('extreme_ad_words', '全国首家'): "high",
    ('extreme_ad_words', '全网首发'): "high",
    ('extreme_ad_words', '首款'): "medium",
    ('extreme_ad_words', '首家'): "medium",
    ('extreme_ad_words', '独家'): "medium",
    ('extreme_ad_words', '独家配方'): "medium",
    ('extreme_ad_words', '首发'): "medium",
    ('extreme_ad_words', '首席'): "medium",
    ('extreme_ad_words', '首府'): "medium",
    ('extreme_ad_words', '首屈一指'): "medium",
    ('extreme_ad_words', '首次'): "medium",
    ('extreme_ad_words', '全国销量冠军'): "high",
    ('extreme_ad_words', '填补国内空白'): "high",
    ('extreme_ad_words', '独创'): "medium",
    ('extreme_ad_words', '开发者'): "medium",
    ('extreme_ad_words', '缔造者'): "medium",
    ('extreme_ad_words', '创始者'): "medium",
    ('extreme_ad_words', '发明者'): "medium",
    ('extreme_ad_words', '绝对值'): "high",
    ('extreme_ad_words', '绝对'): "high",
    ('extreme_ad_words', '大牌'): "medium",
    ('extreme_ad_words', '精确'): "medium",
    ('extreme_ad_words', '超赚'): "high",
    ('extreme_ad_words', '领导品牌'): "high",
    ('extreme_ad_words', '领先上市'): "high",
    ('extreme_ad_words', '巨星'): "medium",
    ('extreme_ad_words', '著名'): "medium",
    ('extreme_ad_words', '奢侈'): "medium",
    ('extreme_ad_words', '世界领先'): "high",
    ('extreme_ad_words', '遥遥领先'): "high",
    ('extreme_ad_words', '金牌'): "medium",
    ('extreme_ad_words', '名牌'): "medium",
    ('extreme_ad_words', '优秀'): "low",
    ('extreme_ad_words', '王牌'): "medium",
    ('extreme_ad_words', '销量冠军'): "high",
    ('extreme_ad_words', '永久'): "medium",
    ('extreme_ad_words', '掌门人'): "medium",
    ('extreme_ad_words', '领袖品牌'): "high",
    ('extreme_ad_words', '领袖'): "medium",
    ('extreme_ad_words', '领导者'): "medium",
    ('extreme_ad_words', '引领'): "low",
    ('extreme_ad_words', '创领'): "low",
    ('extreme_ad_words', '领航'): "low",
    ('extreme_ad_words', '耀领'): "low",
    ('extreme_ad_words', '绝无仅有'): "medium",
    ('extreme_ad_words', '史无前例'): "high",
    ('extreme_ad_words', '前无古人'): "high",
    ('extreme_ad_words', '前无古人后无来者'): "high",
    ('extreme_ad_words', '万能'): "medium",
    ('extreme_ad_words', '百分之百'): "medium",
    ('extreme_ad_words', '100%'): "medium",
    ('extreme_ad_words', '国际品质'): "medium",
    ('extreme_ad_words', '高档'): "medium",
    ('extreme_ad_words', '正品'): "low",
    ('extreme_ad_words', '至尊'): "medium",
    ('extreme_ad_words', '至臻'): "medium",
    ('extreme_ad_words', '臻品'): "medium",
    ('extreme_ad_words', '臻致'): "medium",
    ('extreme_ad_words', '臻席'): "medium",
    ('extreme_ad_words', '压轴'): "medium",
    ('extreme_ad_words', '问鼎'): "medium",
    ('extreme_ad_words', '空前'): "medium",
    ('extreme_ad_words', '绝后'): "medium",
    ('extreme_ad_words', '绝版'): "medium",
    ('extreme_ad_words', '无双'): "medium",
    ('extreme_ad_words', '非此莫属'): "medium",
    ('extreme_ad_words', '前所未有'): "medium",
    ('extreme_ad_words', '无人能及'): "medium",
    ('extreme_ad_words', '鼎级'): "medium",
    ('extreme_ad_words', '鼎冠'): "medium",
    ('extreme_ad_words', '定鼎'): "medium",
    ('extreme_ad_words', '翘楚之作'): "medium",
    ('extreme_ad_words', '不可再生'): "medium",
    ('extreme_ad_words', '无与伦比'): "medium",
    ('extreme_ad_words', '卓越'): "low",
    ('extreme_ad_words', '卓著'): "low",
    ('extreme_ad_words', '完美'): "medium",
    ('extreme_ad_words', '淋漓尽致'): "medium",
    ('extreme_ad_words', '珍稀'): "medium",
    ('extreme_ad_words', '臻稀'): "medium",
    ('extreme_ad_words', '稀少'): "low",
    ('extreme_ad_words', '稀世珍宝'): "medium",
    ('extreme_ad_words', '千金难求'): "medium",
    ('extreme_ad_words', '世所罕见'): "medium",
    ('extreme_ad_words', '不可多得'): "medium",
    ('extreme_ad_words', '空前绝后'): "medium",
    ('extreme_ad_words', '屈指可数'): "medium",
    ('extreme_ad_words', '冠军'): "medium",
    ('extreme_ad_words', '王者'): "medium",
    ('extreme_ad_words', '三甲'): "medium",
    ('extreme_ad_words', '十强'): "medium",
    ('state_sensitive_words', '国家领导人'): "critical",
    ('state_sensitive_words', '领导人'): "critical",
    ('state_sensitive_words', '领导'): "critical",
    ('state_sensitive_words', '行政机关'): "critical",
    ('state_sensitive_words', '政府机关'): "critical",
    ('state_sensitive_words', '处级干部'): "critical",
    ('state_sensitive_words', '警察'): "critical",
    ('state_sensitive_words', '交警'): "critical",
    ('state_sensitive_words', '国徽'): "critical",
    ('state_sensitive_words', '国旗'): "critical",
    ('state_sensitive_words', '国歌'): "critical",
    ('state_sensitive_words', '党徽'): "critical",
    ('state_sensitive_words', '国家领导人画像'): "critical",
    ('state_sensitive_words', '社会主义核心价值观'): "critical",
    ('state_sensitive_words', '邪教'): "critical",
    ('state_sensitive_words', '非法宗教'): "critical",
    ('state_sensitive_words', '交通管制'): "high",
    ('state_sensitive_words', '政策原因'): "high",
    ('state_sensitive_words', '政务'): "high",
    ('state_sensitive_words', '政府'): "high",
    ('state_sensitive_words', '国家免检'): "high",
    ('state_sensitive_words', '国家级产品'): "high",
    ('state_sensitive_words', '特供'): "high",
    ('state_sensitive_words', '专供'): "high",
    ('state_sensitive_words', '专家推荐'): "medium",
    ('state_sensitive_words', '人民币图样'): "high",
    ('state_sensitive_words', '老字号'): "medium",
    ('state_sensitive_words', '中国驰名商标'): "high",
    ('state_sensitive_words', '开门红'): "medium",
    ('state_sensitive_words', '火热开抢'): "medium",
    ('state_sensitive_words', '庆祝'): "low",
    ('state_sensitive_words', '狂欢'): "low",
    ('state_sensitive_words', '疫情'): "medium",
    ('state_sensitive_words', '防疫补贴'): "high",
    ('state_sensitive_words', '抗疫英雄'): "medium",
    ('state_sensitive_words', '医护人员'): "low",
    ('state_sensitive_words', '志愿者'): "low",
    ('state_sensitive_words', '社区工作者'): "low",
    ('state_sensitive_words', '网红'): "low",
    ('state_sensitive_words', '明星'): "low",
    ('state_sensitive_words', '行政用车'): "high",
    ('state_sensitive_words', '处级领导用的'): "critical",
    ('inducement_fraud_words', '点击领奖'): "high",
    ('inducement_fraud_words', '恭喜获奖'): "high",
    ('inducement_fraud_words', '全民免单'): "high",
    ('inducement_fraud_words', '点击有惊喜'): "medium",
    ('inducement_fraud_words', '点击获取'): "medium",
    ('inducement_fraud_words', '点击转身'): "medium",
    ('inducement_fraud_words', '点击试穿'): "medium",
    ('inducement_fraud_words', '点击翻转'): "medium",
    ('inducement_fraud_words', '领取奖品'): "high",
    ('inducement_fraud_words', '非转基因更安全'): "high",
    ('inducement_fraud_words', '售罄'): "low",
    ('inducement_fraud_words', '售空'): "low",
    ('inducement_fraud_words', '再不抢就没了'): "high",
    ('inducement_fraud_words', '不会再便宜'): "high",
    ('inducement_fraud_words', '不会再便宜了'): "high",
    ('inducement_fraud_words', '错过不再'): "high",
    ('inducement_fraud_words', '错过即无'): "high",
    ('inducement_fraud_words', '错过就没机会了'): "high",
    ('inducement_fraud_words', '未曾有过的'): "medium",
    ('inducement_fraud_words', '万人疯抢'): "high",
    ('inducement_fraud_words', '全民疯抢'): "high",
    ('inducement_fraud_words', '抢疯了'): "high",
    ('inducement_fraud_words', '抢购'): "high",
    ('inducement_fraud_words', '抢爆'): "high",
    ('inducement_fraud_words', '秒杀'): "high",
    ('inducement_fraud_words', '秒杀价'): "high",
    ('inducement_fraud_words', '跳楼价'): "high",
    ('inducement_fraud_words', '超大福利'): "high",
    ('inducement_fraud_words', '免费领'): "high",
    ('inducement_fraud_words', '免费住'): "medium",
    ('inducement_fraud_words', '零距离'): "medium",
    ('inducement_fraud_words', '价格你来定'): "medium",
    ('inducement_fraud_words', '抽奖'): "high",
    ('inducement_fraud_words', '打赏'): "high",
    ('inducement_fraud_words', '发红包'): "high",
    ('inducement_fraud_words', '金钱'): "high",
    ('inducement_fraud_words', '红包'): "high",
    ('inducement_fraud_words', '低价引流'): "high",
    ('inducement_fraud_words', '粉丝灯牌'): "medium",
    ('inducement_fraud_words', '灯牌'): "medium",
    ('inducement_fraud_words', '礼物'): "medium",
    ('inducement_fraud_words', '上飞机'): "medium",
    ('inducement_fraud_words', '保时捷墨镜'): "medium",
    ('inducement_fraud_words', '拍了'): "medium",
    ('inducement_fraud_words', '想要'): "medium",
    ('inducement_fraud_words', '666'): "medium",
    ('inducement_fraud_words', '报名'): "medium",
    ('inducement_fraud_words', '扣666'): "medium",
    ('inducement_fraud_words', '倒计时'): "low",
    ('inducement_fraud_words', '趁现在'): "low",
    ('inducement_fraud_words', '仅限'): "medium",
    ('inducement_fraud_words', '随时结束'): "high",
    ('inducement_fraud_words', '随时涨价'): "high",
    ('inducement_fraud_words', '马上降价'): "high",
    ('inducement_fraud_words', '特惠趴'): "medium",
    ('inducement_fraud_words', '购物大趴'): "medium",
    ('inducement_fraud_words', '闪购'): "medium",
    ('inducement_fraud_words', '几天几夜'): "medium",
    ('inducement_fraud_words', '周年庆'): "medium",
    ('inducement_fraud_words', '品牌团'): "medium",
    ('inducement_fraud_words', '今天错过'): "high",
    ('inducement_fraud_words', '明天就没有这个优惠了'): "high",
    ('contact_guidance_words', '微信'): "critical",
    ('contact_guidance_words', '加微信'): "critical",
    ('contact_guidance_words', '微信号'): "critical",
    ('contact_guidance_words', '加我'): "critical",
    ('contact_guidance_words', '我加你'): "critical",
    ('contact_guidance_words', '微信截图'): "critical",
    ('contact_guidance_words', '二维码'): "critical",
    ('contact_guidance_words', '扫二维码'): "critical",
    ('contact_guidance_words', '电话号码'): "critical",
    ('contact_guidance_words', '手机号'): "critical",
    ('contact_guidance_words', '电话'): "high",
    ('contact_guidance_words', '地址'): "critical",
    ('contact_guidance_words', '加主播'): "critical",
    ('contact_guidance_words', '私信主播'): "critical",
    ('contact_guidance_words', '私下聊'): "critical",
    ('contact_guidance_words', '私下交易'): "critical",
    ('contact_guidance_words', '私下销售'): "critical",
    ('contact_guidance_words', '绕过平台'): "critical",
    ('contact_guidance_words', 'qq'): "high",
    ('contact_guidance_words', '后台'): "high",
    ('contact_guidance_words', '私域'): "high",
    ('contact_guidance_words', '留联系方式'): "high",
    ('contact_guidance_words', '小红书'): "high",
    ('contact_guidance_words', '快手'): "high",
    ('contact_guidance_words', '报价'): "high",
    ('contact_guidance_words', '优惠'): "medium",
    ('superstition_words', '招财'): "medium",
    ('superstition_words', '好运'): "medium",
    ('superstition_words', '算命'): "medium",
    ('superstition_words', '招财进宝'): "medium",
    ('superstition_words', '健康富贵'): "medium",
    ('superstition_words', '提升运气'): "medium",
    ('superstition_words', '有助事业'): "medium",
    ('superstition_words', '护身'): "medium",
    ('superstition_words', '平衡正负能量'): "medium",
    ('superstition_words', '消除精神压力'): "medium",
    ('superstition_words', '调和气压'): "medium",
    ('superstition_words', '逢凶化吉'): "medium",
    ('superstition_words', '时来运转'): "medium",
    ('superstition_words', '万事亨通'): "medium",
    ('superstition_words', '旺人'): "medium",
    ('superstition_words', '旺财'): "medium",
    ('superstition_words', '助吉避凶'): "medium",
    ('superstition_words', '转富招福'): "medium",
    ('incivility_words', '黑鬼'): "critical",
    ('incivility_words', '尼哥'): "critical",
    ('incivility_words', '杂种'): "critical",
    ('incivility_words', '东亚病夫'): "critical",
    ('incivility_words', '小日本'): "critical",
    ('incivility_words', '大男子主义'): "medium",
    ('incivility_words', '普信男'): "medium",
    ('incivility_words', '单身狗'): "medium",
    ('incivility_words', '瞎逼逼'): "critical",
    ('incivility_words', '垃圾'): "medium",
    ('incivility_words', '贵族'): "medium",
    ('incivility_words', '高贵'): "medium",
    ('incivility_words', '上流'): "medium",
    ('incivility_words', '富人区'): "medium",
    ('incivility_words', '名门'): "medium",
    ('incivility_words', '阶层'): "medium",
    ('incivility_words', '阶级'): "medium",
    ('incivility_words', '血腥'): "high",
    ('incivility_words', '暴力'): "high",
    ('incivility_words', '赌博'): "high",
    ('incivility_words', '抽烟'): "low",
    ('incivility_words', '喝酒'): "low",
    ('ip_event_words', '世界杯'): "high",
    ('ip_event_words', '冬奥会'): "high",
    ('ip_event_words', '奥林匹克运动会'): "high",
    ('ip_event_words', '双十一'): "medium",
    ('ip_event_words', '双十二'): "medium",
    ('ip_event_words', '米老鼠'): "medium",
    ('ip_event_words', '马里奥'): "medium",
    ('ip_event_words', '吉祥物'): "medium",
    ('ip_event_words', 'IP形象'): "medium",
    ('ip_event_words', '公众人物形象'): "medium",
}

# 词库元数据（缺失才新增）
_LIBRARIES = {
    "used_car_sales_base": ("二手车销售基础违禁词", "二手车销售场景通用违禁词库"),
    "finance_compliance": ("金融方案合规词库", "金融方案承诺相关合规词库"),
    "vehicle_condition_risk": ("车况承诺风险词", "车况承诺相关风险词库"),
    "extreme_ad_words": ("极限用语/绝对化用语", "直播极限用语与绝对化用语风险词库"),
    "state_sensitive_words": ("涉政/权威/国家敏感词", "涉政权威国家敏感词库"),
    "inducement_fraud_words": ("诱导/欺诈/限时消费词", "诱导欺诈限时消费风险词库"),
    "contact_guidance_words": ("线下引流/联系方式引导词", "线下引流与联系方式引导词库"),
    "superstition_words": ("迷信用语", "直播间迷信用语词库"),
    "incivility_words": ("不文明/歧视用语", "不文明与歧视用语词库"),
    "ip_event_words": ("版权/赛事/IP 词", "版权赛事IP风险词库"),
}


def upgrade() -> None:
    # 词库：缺失才新增，不覆盖已有配置（规则 7）
    conn = op.get_bind()
    for key, (name, desc) in _LIBRARIES.items():
        exists = conn.execute(
            sa.text("SELECT 1 FROM forbidden_word_libraries WHERE library_key = :k"),
            {"k": key},
        ).scalar()
        if not exists:
            conn.execute(
                sa.text(
                    "INSERT INTO forbidden_word_libraries (library_key, name, description, scope, enabled, sort_order) "
                    "VALUES (:k, :n, :d, 'global', true, 0)"
                ),
                {"k": key, "n": name, "d": desc},
            )
    # 词条：safe_word=NULL，enabled=true，ON CONFLICT DO NOTHING 幂等（规则 5/6/9）
    for (key, word), sev in _SEED.items():
        lib_id = conn.execute(
            sa.text("SELECT id FROM forbidden_word_libraries WHERE library_key = :k"),
            {"k": key},
        ).scalar()
        if lib_id is None:
            continue  # 词库缺失（不应发生，防御）
        conn.execute(
            sa.text(
                "INSERT INTO forbidden_words (library_id, word, safe_word, severity, enabled, hit_count) "
                "VALUES (:l, :w, NULL, :s, true, 0) "
                "ON CONFLICT (library_id, word) DO NOTHING"
            ),
            {"l": lib_id, "w": word, "s": sev},
        )


def downgrade() -> None:
    # 规则 10：downgrade 不删除词条，只回退版本标记（无数据变更）
    pass

